parameters:
    pack_export_configuration:
        armors-and-shields:
            dto: App\DTO\Export\ArmorsAndShields
            packName: pf1.armors-and-shields.json
        bestiary-00:
            dto: App\DTO\Export\Bestiary
            packName: pf1-bestiary.bestiary-00.json
            label: Bestiaire 00+
        bestiary-02:
            dto: App\DTO\Export\Bestiary
            packName: pf1-bestiary.bestiary-02.json
            label: Bestiaire 02+
        bestiary-04:
            dto: App\DTO\Export\Bestiary
            packName: pf1-bestiary.bestiary-04.json
            label: Bestiaire 04+
        bestiary-06:
            dto: App\DTO\Export\Bestiary
            packName: pf1-bestiary.bestiary-06.json
            label: Bestiaire 06+
        bestiary-08:
            dto: App\DTO\Export\Bestiary
            packName: pf1-bestiary.bestiary-08.json
            label: Bestiaire 08+
        bestiary-11:
            dto: App\DTO\Export\Bestiary
            packName: pf1-bestiary.bestiary-11.json
            label: Bestiaire 11+
        bestiary-15:
            dto: App\DTO\Export\Bestiary
            packName: pf1-bestiary.bestiary-15.json
            label: Bestiaire 15+
        bestiary-20:
            dto: App\DTO\Export\Bestiary
            packName: pf1-bestiary.bestiary-20.json
            label: Bestiaire 20+
        class-abilities:
            dto: App\DTO\Export\ClassAbilities
            packName: pf1.class-abilities.json
        classes:
            dto: App\DTO\Export\Classes
            packName: pf1.classes.json
            entity: App\Entity\TermClass
        commonbuffs:
            dto: App\DTO\Export\CommonBuffs
            packName: pf1.commonbuffs.json
            entity: App\Entity\TermCommonBuff
        conditions:
            dto: App\DTO\Export\Conditions
            packName: pf1.conditions.json
        feats:
            dto: App\DTO\Export\Feats
            packName: pf1.feats.json
            entity: App\Entity\TermFeat
        items:
            dto: App\DTO\Export\Items
            packName: pf1.items.json
            entity: App\Entity\TermItem
        monster-templates:
            dto: App\DTO\Export\MonsterTemplates
            packName: pf1.monster-templates.json
        mythic-paths:
            dto: App\DTO\Export\MythicPaths
            packName: pf1.mythicpaths.json
        races:
            dto: App\DTO\Export\Races
            packName: pf1.races.json
            entity: App\Entity\TermRace
        racial-hd:
            dto: App\DTO\Export\RacialHD
            packName: pf1.racialhd.json
        roll-tables:
            dto: App\DTO\Export\RollTables
            packName: pf1.roll-tables.json
        sample-macros:
            dto: App\DTO\Export\SampleMacros
            packName: pf1.sample-macros.json
        skills:
            dto: App\DTO\Export\Skills
            packName: pf1.skills.json
        spells:
            dto: App\DTO\Export\Spells
            packName: pf1.spells.json
            entity: App\Entity\TermSpell
        ultimate-equipment:
            dto: App\DTO\Export\UltimateEquipment
            packName: pf1.ultimate-equipment.json
        weapons-and-ammo:
            dto: App\DTO\Export\WeaponsAndAmmo
            packName: pf1.weapons-and-ammo.json
